name: publish

on:
  release:
    types:
      - published

jobs:
  crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: login
        run: echo ${{ secrets.CRATES_IO_TOKEN }} | cargo login

      - name: publish
        run: cargo publish
